backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img/icons"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["flutter", "dart", "web", "desktop", "app", "devblog", "news"]
  - label: "Skills"
    name: "skills"
    editor:
      preview: false
    files:
      - label: "SoftSkills"
        name: "softskills"
        file: "src/_data/softskills.yaml"
        fields:
          - label: Soft Skills Items
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Percent, name: percent, widget: number }
      - label: "Front-End Skills"
        name: "frontend"
        file: "src/_data/frontend.yaml"
        fields:
          - label: Front End
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Back-End Skills"
        name: "backend"
        file: "src/_data/backend.yaml"
        fields:
          - label: Back End
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Databases Skills"
        name: "databases"
        file: "src/_data/databases.yaml"
        fields:
          - label: Databases
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Compiled Languages"
        name: "compiledlanguages"
        file: "src/_data/compiledlanguages.yaml"
        fields:
          - label: Compiled Languages
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Other"
        name: "other"
        file: "src/_data/other.yaml"
        fields:
          - label: Other
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }